### ISSUE TITLE
getting error when query transaction

### ISSUE THREAD

**Issue by kenken64** [perfectmak/libra-core#24]
```
/home/kenneth/Projects/facebook_libra_workshop/server/node_modules/libra-
core/build/client/Decoder.js:39
        const signedTransaction = signedTransactionWP.getSignedTransaction();
                                                      ^

TypeError: Cannot read property 'getSignedTransaction' of undefined
    at ClientDecoder.decodeSignedTransactionWithProof (/home/kenneth/Projects/facebook_libra_workshop/server/node_modules/libra-core/build/client/Decoder.js:39:55)
    at /home/kenneth/Projects/facebook_libra_workshop/server/node_modules/libra-core/build/client/index.js:109:38
    at Object.onReceiveStatus (/home/kenneth/Projects/facebook_libra_workshop/server/node_modules/grpc/src/client_interceptors.js:1207:9)
    at InterceptingListener._callNext (/home/kenneth/Projects/facebook_libra_workshop/server/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/kenneth/Projects/facebook_libra_workshop/server/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/kenneth/Projects/facebook_libra_workshop/server/node_modules/grpc/src/client_interceptors.js:845:24)
```

**Comment by kenken64** [comment]
```javascript
async function getTransactions(accountNumber, sequenceNumber, cb) {
  const transaction = await client.getAccountTransaction(
    accountNumber,
    sequenceNumber
  );
  cb(transaction);
}

app.get(`${API_URL}/transactions/:address/:sequenceNo`, (req, res) => {
  const address = req.params.address || FALLBACK_ADDRESS;
  console.log(address);
  const sequenceNumber = req.params.sequenceNo || 0;
  try {
    getTransactions(address, sequenceNumber, transaction => {
      console.log(transaction);
      res.status(200).json(transaction);
    });
  } catch (error) {
    console.log(error);
  }
});

```

**Comment by kenken64** [comment]
I know why I have not done a coin transfer then I query an unavailable transactions

**Comment by kenken64** [comment]
I think I would like to re-open this issue there isn't any way to catch the TypeError from outside so I can flag out that no query record is created yet

**Comment by perfectmak** [comment]
This is true. I thought I already caught the case for when a transaction doesn't exist. I'll queue this fix in the current upcoming fixes. Or if you have enough bandwith, your contribution would be welcome
